# Generated by Django 2.1.5 on 2021-08-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20210803_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='description',
            field=models.TextField(blank=True, verbose_name='describe'),
        ),
    ]
