# Generated by Django 2.1.5 on 2021-08-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_dog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinfo',
            name='contactnumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinfo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='describe'),
        ),
        migrations.AddField(
            model_name='salesinfo',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breedname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='describe'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dog_images'),
        ),
        migrations.RemoveField(
            model_name='dog',
            name='salesinfo',
        ),
        migrations.AddField(
            model_name='dog',
            name='salesinfo',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='rango.salesinfo', verbose_name='sales'),
        ),
        migrations.AlterField(
            model_name='salesinfo',
            name='breedname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='salesinfo',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sales_images'),
        ),
    ]
