# Generated by Django 2.1.5 on 2021-08-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20210803_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinfo',
            name='breedname',
            field=models.ForeignKey(blank=True, max_length=128, null=True, on_delete='CASCADE', related_name='name', to='rango.Dog'),
        ),
    ]
