# Generated by Django 2.1.5 on 2021-08-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_auto_20210803_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'samllDog'), (2, 'bigDog'), (3, 'mediumDog')], default=1, verbose_name='size'),
        ),
    ]
