# Generated by Django 2.2 on 2021-08-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_dog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='noone', max_length=128, verbose_name='username')),
                ('content', models.TextField(null=True, verbose_name='content')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='time')),
                ('doginfo', models.ForeignKey(on_delete='CASCADE', to='rango.Dog')),
            ],
            options={
                'verbose_name': 'comments',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
