# Generated by Django 2.2 on 2021-08-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0011_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='doginfo',
        ),
    ]
