# Generated by Django 2.1.5 on 2021-08-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0013_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='dog',
        ),
        migrations.AddField(
            model_name='collection',
            name='clt_dogid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='clt_who',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
