# Generated by Django 2.1.5 on 2021-08-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0014_auto_20210805_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
